git:
  depth: 3

language: php
sudo: required
dist: precise

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi

install:
  - composer install

before_script:
  - ./tests/ci/install.sh
  - npm install

script:
  - ./node_modules/.bin/jshint assets/js/src/*.js
  - ./vendor/bin/phpunit -c tests/phpunit.unit.sqlite.xml
  - ./vendor/bin/phpunit -c tests/phpunit.unit.postgres.xml
  - ./vendor/bin/phpunit -c tests/phpunit.unit.mysql.xml
  - ./vendor/bin/phpunit -c tests/phpunit.functional.sqlite.xml
  - cp ./tests/ci/config.postgres.php $TRAVIS_BUILD_DIR/config.php
  - ./vendor/bin/phpunit -c tests/phpunit.functional.postgres.xml tests/functional/ApiTest.php
  - ./vendor/bin/phpunit -c tests/phpunit.functional.postgres.xml tests/functional/FeverApiTest.php
  - cp ./tests/ci/config.mysql.php $TRAVIS_BUILD_DIR/config.php
  - ./vendor/bin/phpunit -c tests/phpunit.functional.mysql.xml tests/functional/ApiTest.php
  - ./vendor/bin/phpunit -c tests/phpunit.functional.mysql.xml tests/functional/FeverApiTest.php

after_failure:
  - cat apache_error.log
  - cat apache_access.log
